#!/bin/bash
# comprueba que arranca el proceso de awesome antes de ejecutar proceso que
# genera los datos y los envia a awesome.

sleep 2;

while ! pgrep awesome >/dev/null
do
    echo "waiting for 'awsome-wm' to start"
    sleep 2;
done

estado.sh
